In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
#importing datasets  
data_set= pd.read_csv(r"C:\Users\User\Downloads\Real_fake_news.csv")  
# removing redundant spaces from column names
data_set.columns = list(map(lambda a: a.lstrip(), data_set.columns))
data_set = data_set.drop(columns=['Unnamed: 0','Unnamed: 0.1','target','BinaryTarget'])
data_set.head()

author                                          statement  \
0         Jill Terreri  New York is "leading the nation with the lowes...   
1  Eleanor Hildebrandt  “Iowa ranks 45th in the U.S. for internet conn...   
2     Emily Zirkelbach  “FUN FACT: West Virginia is home to zero billi...   
3        Madeline Heim  Says gubernatorial candidate Rebecca Kleefisch...   
4        Sabine Martin  The Biden administration "published a study co...   

                                              source  BinaryNumTarget  
0  NYS Department of Corrections and Community Su...                1  
1                                         Cindy Axne                1  
2                                         David Gura                1  
3                                   Kelda Helen Roys                1  
4                                     Randy Feenstra                1

In [3]:
data_set1 = pd.get_dummies(data_set)
data_set1.head()

BinaryNumTarget  author_Aaron Marshall  author_Aaron Sharockman  \
0                1                      0                        0   
1                1                      0                        0   
2                1                      0                        0   
3                1                      0                        0   
4                1                      0                        0   

   author_Adam Thorp  author_Adrianne Uphold  author_Adriel Bettelheim  \
0                  0                       0                         0   
1                  0                       0                         0   
2                  0                       0                         0   
3                  0                       0                         0   
4                  0                       0                         0   

   author_Al Bernardi  author_Alan Gathright  author_Alan Hovorka  \
0                   0                      0                    0   
1                   0                      0                    0   
2                   0                      0                    0   
3                   0                      0                    0   
4                   0                      0                    0   

   author_Alayna Degenhardt  ...  source_WrongWayRubio.com  \
0                         0  ...                         0   
1                         0  ...                         0   
2                         0  ...                         0   
3                         0  ...                         0   
4                         0  ...                         0   

   source_Xavier Becerra  source_Yard sign  \
0                      0                 0   
1                      0                 0   
2                      0                 0   
3                      0                 0   
4                      0                 0   

   source_Yes On 62 campaign to abolish California's death penalty  \
0                                                  0                 
1                                                  0                 
2                                                  0                 
3                                                  0                 
4                                                  0                 

   source_YouTube videos  source_YourContent  source_Yvette McGee Brown  \
0                      0                   0                          0   
1                      0                   0                          0   
2                      0                   0                          0   
3                      0                   0                          0   
4                      0                   0                          0   

   source_Zach Wahls  source_Zerlina Maxwell  source_teaparty.org  
0                  0                       0                    0  
1                  0                       0                    0  
2                  0                       0                    0  
3                  0                       0                    0  
4                  0                       0                    0  

[5 rows x 6678 columns]

In [4]:
X = data_set1.drop(columns=['BinaryNumTarget'])
y = data_set1['BinaryNumTarget']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=42)

In [5]:
#feature Scaling  
st_x= StandardScaler()    
x_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)  
y_test

1654    1
1101    1
1149    1
2763    0
3145    0
       ..
2187    1
1538    1
3407    0
1807    1
3938    0
Name: BinaryNumTarget, Length: 1461, dtype: int64

In [6]:
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [7]:
y_pred = knn.predict(X_test)

In [8]:
confusion_matrix(y_test, y_pred)

array([[616,  89],
       [ 72, 684]], dtype=int64)

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8898015058179329

In [10]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred)

(array([0.89534884, 0.88486417]),
 array([0.87375887, 0.9047619 ]),
 array([0.88442211, 0.89470242]),
 array([705, 756], dtype=int64))

In [11]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.8848641655886158

In [12]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.9047619047619048

In [13]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.8947024198822761

In [14]:
knn = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [15]:
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.8959616700889802